### ISSUE TITLE
Repost tensorflow_2.10 snapshot?

### ISSUE THREAD

**Issue by amanda321** [eaplatanios/tensorflow_scala#103]
I place the following line in my build.sbt file, as specified by your installationinstructions:
`libraryDependencies += "org.platanios" %% "tensorflow" % "0.1.0-SNAPSHOT"`

I get the following error:
```
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/platanios/tensorflow_2.10/0.1.0-SNAPSHOT/tensorflow_2.10-0.1.0-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.platanios#tensorflow_2.10;0.1.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
```

When I look at https://oss.sonatype.org/content/repositories/snapshots/org/platanios/, I only see snapshots for Scala 2.11, 2.12.  Indeed, if I change the line in my build.sbt file to:
`libraryDependencies += "org.platanios" % "tensorflow_2.11" % "0.2.0-SNAPSHOT"`
I am able to get the snapshot. However, I need the 2.10 version for my project.

Could you reupload the tensorflow_2.10 snapshot?

**Comment by eaplatanios** [comment]
@amanda321 I think that the current version does not compile for 2.10 anymore, but I'll check today. Why do you need 2.10 specifically and cannot work with 2.11 or 2.12?

**Comment by amanda321** [comment]
A bit of a SBT rookie, but SBT was complaining that there were incompatible Scala versions used between different packages. And it looked like most of the other packages were using Scala 2.10.

But no worries on checking. I found an alternative solution that doesn't require tensorflow-scala!

**Comment by eaplatanios** [comment]
@amanda321 I'm glad you figured it out. :)
