### ISSUE TITLE
Filter logs coming from TensorFlow

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#105]
When running on GPU, I get annoying error messages in the log. There doesn't seem to be a real problem though.
 
```[error] 2018-05-12 12:50:56.575522: E tensorflow/core/grappler/clusters/utils.cc:127] Not found: TF GPU device with id 0 was not registered```

I tried to filter that using logback filters, but the filters are ignored for these messages. They work only for my own log messages for some reason. Any idea how we can filter these messages?

Info level messages are also logged as error for some reason:
```[error] 2018-05-12 12:50:34.390298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0```

**Comment by eaplatanios** [comment]
Yeah I have noticed those and talked to some TensorFlow people about them. The only reason to filter them is to set the `TF_CPP_MIN_LOG_LEVEL` environment variable:

- `0`:  Debug level (default).
- `1`: Warning level.
- `2`: Error level.
- `3`: Fatal level.
