### ISSUE TITLE
Malformed exception under Ubuntu 16.0.4

### ISSUE THREAD

**Issue by fredfeng** [eaplatanios/tensorflow_scala#107]
Hi,
I am getting the following exception during the initialization of the library.
It works well on my Mac and the issue only happens under Ubuntu machines. 

[error] (run-main-0) java.lang.Exception: Malformed assigned device 'CPU'
[error] Current trace: List()
[error] java.lang.Exception: Malformed assigned device 'CPU'
[error] Current trace: List()
[error] 	at rlSync.SimulationHandle.toRollout(StatefulRLProblem.scala:50)
[error] 	at rlSync.SimulationHandle.toRollout$(StatefulRLProblem.scala:29)
[error] 	at rlSync.OCamlInterface$OCamlHandle.toRollout(OCamlInterface.scala:116)
[error] 	at rlSync.PolicyGradient.$anonfun$train$2(PolicyGradient.scala:169)
[error] 	at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
[error] 	at rlSync.PolicyGradient.$anonfun$train$1(PolicyGradient.scala:166)
[error] 	at rlSync.PolicyGradient.$anonfun$train$1$adapted(PolicyGradient.scala:164)
[error] 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
[error] 	at scala.collection.Iterator$SliceIterator.next(Iterator.scala:259)
[error] 	at scala.collection.Iterator$$anon$20.next(Iterator.scala:874)
[error] 	at scala.collection.Iterator$$anon$20.next(Iterator.scala:870)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at rlSync.TrainingCenter$.main(TrainingCenter.scala:158)
[error] 	at rlSync.TrainingCenter.main(TrainingCenter.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1172)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1167)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / run) Nonzero exit code: 1

**Comment by eaplatanios** [comment]
This has now been fixed. :)
