### ISSUE TITLE
MNIST Example does not compile: diverging implicit expansion

### ISSUE THREAD

**Issue by GratefulTony** [eaplatanios/tensorflow_scala#108]
`Error:(28, 50) diverging implicit expansion for type org.platanios.tensorflow.api.implicits.helpers.OutputToTensor.Aux[org.platanios.tensorflow.api.tensorDataHelper.OutputType,org.platanios.tensorflow.api.Tensor]
starting with method productOutputToTensorConstructor in object OutputToTensor
Error occurred in an application involving default arguments.
    val trainImages = tf.data.TensorSlicesDataset(dataSet.trainImages)`

**Comment by GratefulTony** [comment]
Source from example verbatim pasted into a new project does not compile on either 0.1.0 or 0.1.1

Unsure whether I am missing imports?

**Comment by eaplatanios** [comment]
@GratefulTony Please use version 0.2.0-SNAPSHOT. I will update the website accordingly soon.
