### ISSUE TITLE
Too many redirection on the site

### ISSUE THREAD

**Issue by leonard-IMBERT** [eaplatanios/tensorflow_scala#109]
I got an error from google chrome. It tells me `eaplatanios.github.io redirect you too many times.` I don't think it's the expected feature ^^'

I tried on google chrome and firefox and got the same result :/

**Comment by leonard-IMBERT** [comment]
My bad.
Fun fact: avast was doing shit with my internet connection

**Comment by leonard-IMBERT** [comment]
After some research, it seems you have wierd redirection that are none ending:
`302 /tensorflow_scala -> /Xadjz/tensorflow_scala`
`302 /Xadjz/tensorflow_scala -> /KKcNz/tensorflow_scala`
`302 /KKcNz/tensorflow_scala -> /tensorflow_scala`
`302 /tensorflow_scala -> /MXQWZ/tensorflow_scala`

**Comment by leonard-IMBERT** [comment]
Seems good now

**Comment by eaplatanios** [comment]
@leonard-IMBERT Sorry there was some issue due to renewing my domain registration.
