### ISSUE TITLE
Sparse Placeholder default constructor triggers exception

### ISSUE THREAD

**Issue by alexisdurieux** [eaplatanios/tensorflow_scala#111]
Maybe, I'm missing something but it seems that the sparsePlaceholder constructor is always triggering the following error: 
`An error occurredorg.platanios.tensorflow.api.core.package$exception$InvalidShapeException: Shape '[?]' must have the same rank as shape '[?, ?]'`

I have tried many workarounds, but the initial line triggering the error is:
`val inputs: SparseOutput = tf.sparsePlaceholder(INT64, Shape(-1, cardinality))`

**Comment by eaplatanios** [comment]
@alexisdurieux Just to make sure I understand correctly, does that error occur when you execute that line, or when you execute `session.run(...)` later on?

**Comment by alexisdurieux** [comment]
@eaplatanios it happens when I execute the line. Sorry if that's not very clear !

**Comment by eaplatanios** [comment]
@alexisdurieux I'm sorry that was my bad. The bug should be fixed now. :)

**Comment by alexisdurieux** [comment]
Thanks for you reactivity !
