### ISSUE TITLE
corrupted size vs. prev_size [libtensorflow.so+0x724284]

### ISSUE THREAD

**Issue by DirkToewe** [eaplatanios/tensorflow_scala#115]
This may likely be an issue of the native libraries, but since it might affect others as well, I'm posting it here. Plus it could maybe be an issue with concurrency?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007feb221dc284, pid=6389, tid=0x00007febb9286700
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtensorflow.so+0x724284]

[error] corrupted size vs. prev_size
[info] # C  [libtensorflow.so+0x724284]
[error] java.lang.RuntimeException: Nonzero exit code returned from runner: 134
[error] 	at sbt.ForkRun.processExitCode$1(Run.scala:33)
[error] 	at sbt.ForkRun.run(Run.scala:42)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1163)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1158)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
This bug can be reliably reproduced on 2 PCs:
  - AMD FX-8150 / GTX1080Ti / Ubuntu 18.04
  - AMD Phenom II X4 940 / GT640 / Ubuntu 16.04

Reading `corrupted size vs. prev_size`, I tried it with:
  - `"0.2.4" classifier "linux-gpu-x86_64"`
  - 0.2.4 with custom build (cuda, -march=native, jemalloc)
  - 0.2.4 with custom build (cuda, -march=native, tcmalloc)

I did not yet encounter this issue with `"0.2.4" classifier "linux-cpu-x86_64"`. But the problem is it's ~25x slower so it may still fail in a day or so. In the meantime I'm going to make a debug build and see if GDB may be able to tell me more.

**Comment by DirkToewe** [comment]
All I managed to find out is that there's a memory leak and it seems happen during the creation of new Tensors. The following example blows on my puny 32gb machine after run 67:
```scala
    val in_x = tf.placeholder(FLOAT32, Shape(-1,-1) )
    val op_2x = 2*in_x
    val session = Session()

    val rng = new Random(1337)
    try {
      for( run <- 0 to 1024*1024 )
      {
        println(f"Run$run%4d")
        val nRows = rng.nextInt(256*1024)+1
        val nCols = 15
        val arr = Array.fill(nRows*nCols)(rng.nextFloat)
        val ten = (arr: Tensor) reshape Shape(-1,15)
        val Seq(x2: Tensor) = session.run( in_x -> ten, Seq(op_2x) )
        assert( x2.entriesIterator.zipWithIndex.forall{ case (f,i) => f == 2*arr(i) } )
      }
    } finally { session.close() }
```
Tensors are not added to the computation graph, right?

**Comment by eaplatanios** [comment]
@DirkToewe I do use a disposing thread in the background to dispose unused resources. It's using phantom references. I wonder if the way in which these implicits interact messes up with the garbage collector somehow and prevents it from collecting the intermediate tensors that are created. I'll try to look into this this weekend.

**Comment by DirkToewe** [comment]
It could also be that `Disposer` is crashing but I won't be able to check until monday.

**Comment by eaplatanios** [comment]
@DirkToewe Sorry for the super late followup, but did you end up looking further into this?

**Comment by DirkToewe** [comment]
Nothing much new to report, I'm afrad. The disposert thread is running all the time. With Scala 2.11 in Jupyter Notebook (jupyter), I just discovered an issue that may be related:

![disposer_issues](https://user-images.githubusercontent.com/8115342/42904297-d8fd945a-8ad4-11e8-8401-8d74168d97a2.png)

Could it be that the JVM enqueues the reference *before* the native code is done with it?

**Comment by eaplatanios** [comment]
Thanks for catching that memory leak. Regarding the apply method issue, I think that's a common ambiguity in Scala and may be resolved in Dotty (I'm not 100% sure). I'll look into maybe throwing a more informative error.
