### ISSUE TITLE
Cross-build for Scala 2.11?

### ISSUE THREAD

**Issue by MLnick** [eaplatanios/tensorflow_scala#12]
Would there be interest to allow cross-building for Scala 2.11?

The only issues I had to fix to get it to compile for Scala 2.11 were [here](https://github.com/eaplatanios/tensorflow_scala/blob/5c15299394be649852a2d091312b9b1af0786fba/tensorflow/src/main/scala/org/platanios/tensorflow/api/ops/variables/VariableScope.scala#L302) and [here](https://github.com/eaplatanios/tensorflow_scala/blob/5c15299394be649852a2d091312b9b1af0786fba/tensorflow/src/main/scala/org/platanios/tensorflow/api/ops/variables/VariableStore.scala#L140), where I had to change the form to `new VariableGetter() { ... }` and implement an `override apply` method.

**Comment by MLnick** [comment]
Also the main `tensorflow` JAR build needs to be adjusted - it always gets packaged as `tensorflow` rather than with the Scala version suffix.

**Comment by eaplatanios** [comment]
Thanks a lot for pointing that out! It's now been fixed. :)

**Comment by MLnick** [comment]
Thanks!
