### ISSUE TITLE
Undefined symbols when compiling native tensorflow_ops

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#126]
When trying to compile current master. I'm using the libtensorflow[_framework].so from the 0.3.0-SNAPSHOT releases on MacOS. Do I need a more recent TF build or am I missing something else?

```
...
[info] /usr/local/Cellar/cmake/3.12.1/bin/cmake -E cmake_link_script CMakeFiles/tensorflow_ops.dir/link.txt --verbose=1
[info] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o libtensorflow_ops.so CMakeFiles/tensorflow_ops.dir/ops/beam_search_ops.cc.o CMakeFiles/tensorflow_ops.dir/ops/beam_search_ops_gpu.cu.cc.o CMakeFiles/tensorflow_ops.dir/ops/eager_executor.cc.o CMakeFiles/tensorflow_ops.dir/ops/jvm_callback_op.cc.o CMakeFiles/tensorflow_ops.dir/ops/tensor_handle.cc.o -Wl,-rpath,@loader_path /usr/local/lib/libtensorflow.so /usr/local/lib/libtensorflow_framework.so 
Undefined symbols for architecture x86_64:
  "tensorflow::CopyTensor::ViaDMA(tensorflow::StringPiece, tensorflow::DeviceContext*, tensorflow::DeviceContext*, tensorflow::Device*, tensorflow::Device*, tensorflow::AllocatorAttributes, tensorflow::AllocatorAttributes, tensorflow::Tensor const*, tensorflow::Tensor*, std::__1::function<void (tensorflow::Status const&)>)", referenced from:
      tensorflow::TensorHandle::CopyToDevice(tensorflow::EagerContext*, tensorflow::Device*, tensorflow::TensorHandle**) in tensor_handle.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```

**Comment by eaplatanios** [comment]
@sbrunk Sorry for the delay on this but I've been waiting on some stuff from the TensorFlow team. Is this also happening for the Linux releases?

**Comment by tampler** [comment]
I also encountered similar issue in Ubuntu 16.04. I downloaded the latest TF 1.10.1 *.so files from here: https://www.tensorflow.org/install/install_c
After exporting the LD_LIBRARY_PATH, I checked out this project and did the following:
1. sbt in the prj root
2. When sbt finished the download/compile/build loop, I then
3. Entered  "console" in the sbt shell
4. Tried to declare the tensor from your example with:
```python
import org.platanios.tensorflow.api._
val inputs = tf.placeholder(FLOAT32, Shape(-1, 10))
```
the scala shell returned the following: 

scala> val inputs = tf.placeholder(FLOAT32, Shape(-1, 10))
org.platanios.tensorflow.jni.NotFoundException: /tmp/tensorflow_scala_native_libraries4692364774572197131/libtensorflow_ops.so: undefined symbol: _ZN10tensorflow10CopyTensor6ViaDMAENS_11StringPieceEPNS_13DeviceContextES3_PNS_6DeviceES5_NS_19AllocatorAttributesES6_PKNS_6TensorEPS7_St8functionIFvRKNS_6StatusEEE
  at org.platanios.tensorflow.jni.TensorFlow$.loadOpLibrary(Native Method)
  at org.platanios.tensorflow.jni.TensorFlow$.$anonfun$load$6(TensorFlow.scala:107)
  at scala.Option.foreach(Option.scala:257)
...

**Comment by eaplatanios** [comment]
Could you try again using the latest `0.3.0-SNAPSHOT` and the precompiled binaries distributed with TF Scala? It currently works using the `master` branch of TensorFlow (i.e., the nightly builds).

**Comment by sbrunk** [comment]
Sorry I didn't manage to try it earlier. The error still occurs on macOS using current master 36a9d2bb1e0b5fcddb6a2a4ca30b523c599d2650 and your precompiled TF binaries from Sep 15. I'll try it on Linux tomorrow.

**Comment by eaplatanios** [comment]
@sbrunk I am unable to reproduce this on a Mac. Did you make sure there are no old `libtensorflow[_framework].so` anywhere in your system that are accidentally being picked up?

**Comment by sbrunk** [comment]
Yeah seem like it as it works fine on Linux. Sorry for the noise.

**Comment by eaplatanios** [comment]
@sbrunk No problem at all! Actually this kind of issues is very useful because it's hard for me to test the binaries on multiple machines, and issues related to them appear from time to time. I'm going to release 0.3.0 now that we know this is fine. :)
