### ISSUE TITLE
Does the package have matrix operations? 

### ISSUE THREAD

**Issue by git4sun** [eaplatanios/tensorflow_scala#129]
Like `factorization_ops.WALSModel` in python version?

**Comment by eaplatanios** [comment]
No I haven't really worked on adding support for those, but it shouldn't be too hard to do that, if you need them for your work. I can help with any issues that may come up.

**Comment by git4sun** [comment]
Hi @eaplatanios, Would you please let me know if you have the plan to incorporate these ops? Thanks.

**Comment by eaplatanios** [comment]
@git4sun I've been working on some major design changes in #131. I'll soon finish that and then make a guide that shows have you can add support for the functionality you need.

**Comment by eaplatanios** [comment]
@cosmir17 regarding your second question, TensorFlow tensors are immutable and thus you cannot replace the value at a specific coordinate. You should use `tf.Variable` if you want to change it's values, but you should also probably consider restructuring your code so that you don't have to (sometimes this is possible).

**Comment by cosmir17** [comment]
@eaplatanios, I thought so. Therefore, I asked 'how would I create a copy of...'? Would you be able to help me with the following transportation, please?
```
val matrix = session.run(feeds = Map(x -> state), q);
val something: ndarray[int] <= python code
```
I would like to do something like, **matrix(0, something) = assignment** <= python code

I really appreciate your kindness. Would you mind if I ask another question, please? How can I translate the following code into Scala?
```
current_state = np.asmatrix(np.hstack((a[i:i+number], b, c)))
action_q_vals = self.sess.run(q, feed_dict={x: current_state})
```

Thank you,
cosmir17

**Comment by cosmir17** [comment]
@eaplatanios, for the first part, I did the following,
```
import org.platanios.tensorflow.api.tensors.ops.Basic._
val remaingOldPart = matrix(something, matrix.size.toInt)
val newReplacingPart = matrix(0, something)
val newMatrix = concatenate(Seq(newReplacingPart, remaingOldPart), 0)
```
Hope this will work :)

I am still trying to transport the following
`current_state = np.asmatrix(np.hstack((a[i:i+number], b, c))) //python code`

**Comment by eaplatanios** [comment]
@cosmir17 I believe this might work for you:

```
val currentState = tf.stack(Seq(a(I::i+number), b, c)), axis=1)
```

I'll close this for now. Please feel free to reopen if the issue persists.

**Comment by cosmir17** [comment]
@eaplatanios It was perfectly fine to close this ticket. I used this ticket as a Q&A board as it dealt with a Matrix question. Thank you for your answer.
I tried,
`val currentState = tf.stack(Seq(a(i::i+number::Nil), b, c), axis=1)`
this returned 'Output[Float]'

I want, Tensor[Float]
How can I do a similar thing as 'np.asmatrix' in order to get Tensor[Float]?

Thank you,
cosmir17

**Comment by eaplatanios** [comment]
If you want to deal with `Tensor`s instead of `Output`s try replacing `tf.stack` and `tf.slice` with `tfi.stack` and `tfi.slice`. :)

**Comment by cosmir17** [comment]
Thank you. It compiles!

**Comment by cosmir17** [comment]
One more question, if you don't mind. It regards to a previous comment you made.
> @cosmir17 regarding your second question, TensorFlow tensors are immutable and thus you cannot replace the value at a specific coordinate. You should use `tf.Variable` if you want to change it's values, but you should also probably consider restructuring your code so that you don't have to (sometimes this is possible).

Yes, it's immutable and I don't want to modify it (also as a Scala dev, side effect ..etc). I want to create a new Tensor from an existing one (copying it & modify a specific coordinate value)
```
val myTensor: Tensor[Float] = ???
val floatValue: Float = 1.3f
Something like ====>     'myTensor.copy(myTensor(index1)(index2) = floatValue)'
```
Tensor[Float] is a wrapper. There must be a way.

**Comment by eaplatanios** [comment]
So there didn't use to be a way to do that, but I think there might be one now. I'll look into it and try to add support within the next week.

**Comment by cosmir17** [comment]
I see. I appreciate your support.

**Comment by DirkToewe** [comment]
@cosmir17 You may have already noticed that nested Seqs and Arrays can be easily converted to `Tensor`s. The other way is also possible (albeit not as easily). So if You need to to random access read an write, You can do the following:

```scala
val input: Tensor[Int] = Array(
  Array(1,2, 3),
  Array(5,6, 7),
  Array(8,9,10)
)

val Array(m,n) = input.shape.asArray

// convert Tensor[Int] to Array[Array[Int]]
val arr = Array.tabulate(m,n)(
  (i,j) => input(i,j).scalar
)

for( i <- 0 until m )
  for( j <- 0 until n )
    arr(i)(j) *= 2

// implicitly convert Array[Array[Int]] back to Tensor[Int]
val output: Tensor[Int] = arr
```

Hope this helps

**Comment by cosmir17** [comment]
Hi @DirkToewe, thank you for your kind help. I really appreciate it. I had not been well since yesterday night. I will try it soon. Also, thank you for introducing the low level approach 👍

**Comment by cosmir17** [comment]
Hi @DirkToewe, It works. Thank you very much 👍 I am glad that it works!!!

P.S. I didn't want to use a mutable object (arr) so I was looking for an option. The following code works for a 2d tensor.

val Array(m, n) = input.shape.asArray
val seq = Seq.tabulate(m, n)((i, j) => input(i, j).scalar)
seq.updated(x , seq(x).updated(y, replacingValue))

x, y are indices that I want to change*
