### ISSUE TITLE
fyi - generate functions from ops.pbtxt

### ISSUE THREAD

**Issue by johndpope** [eaplatanios/tensorflow_scala#13]
https://github.com/tensorflow/tensorflow/commit/3f538fadf2dedaeddc295580eaff635c98f1793a

you maybe able to cherry pick this code
https://github.com/tensorflow/tensorflow/tree/3f538fadf2dedaeddc295580eaff635c98f1793a/tensorflow/go/op

**Comment by eaplatanios** [comment]
I have looked into this in the past. You could do this with macros and I have a sample for that somewhere if you're interested. However, I found out that for most ops, there exists a lot of logic in the python layer of the TensorFlow API, ending up with customized implementations for most of them. Thus, I decided this was not necessary for now. What do you think?

**Comment by johndpope** [comment]
I think you could request help from people consuming library. This popped up on radar so just took a quick look through list of things that were still outstanding and this jumped out at me.
no problem. going to close this.
