### ISSUE TITLE
Cant find version 0.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by JoeWells96** [eaplatanios/tensorflow_scala#132]
I saw in https://github.com/eaplatanios/tensorflow_scala/issues/124 you reccomended to use `0.3.0-SNAPSHOT` over `0.2.4` however my sbt is failing to find that version and i can't see it on mvnrepo https://mvnrepository.com/artifact/org.platanios/tensorflow-api. Please advise, thank you

**Comment by eaplatanios** [comment]
@JoeWells96 That is because for snapshot versions you need to use the snapshots repository. In SBT this is done using this, for example:
```
resolvers in ThisBuild += Resolver.sonatypeRepo("snapshots")
```
However, I just released a full `0.3.0` and so can you check if you can use `0.3.0` directly? That is, without the `-SNAPSHOT` part.

**Comment by eaplatanios** [comment]
No problem!:) Does it not find `0.3.0` or is it throwing an error when using it?

**Comment by eaplatanios** [comment]
@JoeWells96 There was an issue with the `0.3.0` release that should have been fixed now so I'm closing this. Please re-open if the issue persists.
