### ISSUE TITLE
ops.Files not exported

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#140]
The ops under [Files](https://github.com/eaplatanios/tensorflow_scala/blob/master/modules/api/src/main/scala/org/platanios/tensorflow/api/ops/Files.scala) like `readFile` and `writeFile`  don't seem to be exported anywhere or am I missing something?

I think it used to be exported under ops.io before some refactoring.

**Comment by eaplatanios** [comment]
Good catch! I must have accidentally removed it. I added it back and it will be included in the next release. :)

**Comment by sbrunk** [comment]
Thanks :)
