### ISSUE TITLE
UnsupportedOperationException when trying to save Tensor with writeNPY

### ISSUE THREAD

**Issue by Spiess** [eaplatanios/tensorflow_scala#142]
When I try to save a tensor using the `writeNPY` function, it always throws an UnsupportedOperationException.

For example, the following code causes the problem for me:
```
val tensor = Tensor(0f, 1.5f, 4.7f)
tensor.writeNPY(Paths.get("test.npy"))
```

**Comment by eaplatanios** [comment]
This is fixed and will be soon published as an updated `0.4.2-SNAPSHOT`. Thanks for catching this bug! :)
