### ISSUE TITLE
Example on how to use TFRecordWriter

### ISSUE THREAD

**Issue by drivenbyentropy** [eaplatanios/tensorflow_scala#151]
Hi! First of all, congratulations for this amazing project. 

I was wondering if you have an example of how to use `TFRecordWriter` and how to create the required `Example` objects that need to be passed to it in order to create a `TFRecord` file. I am using Scala for my  pre-processing and sample exaction pipeline and would ultimately like to be able to write these data to file which could be read by TF APIs in other languages such as Python. 

Thanks!

Edit: I am particularly interested in how to create an `Example` containing one or more Tensors

**Comment by eaplatanios** [comment]
You can see an example of how the `TFRecordWriter` is used [here](https://github.com/eaplatanios/symphony-mt/blob/4d434a97b34a0771cbf658dc1957d31393f3e212/mt/src/main/scala/org/platanios/symphony/mt/models/Inputs.scala#L434). :)
