### ISSUE TITLE
No way to switch / reset default graph

### ISSUE THREAD

**Issue by Spiess** [eaplatanios/tensorflow_scala#155]
In Python TensorFlow there are graph management functions to be able to reset and switch graphs around to allow using multiple different graphs within the same process. I haven't been able to find these functions in TensorFlow Scala and assume that they are not yet implemented.

The specific functions I am missing are [`tf.reset_default_graph`](https://www.tensorflow.org/api_docs/python/tf/reset_default_graph) and [`tf.Graph.as_default`](https://www.tensorflow.org/guide/graphs#programming_with_multiple_graphs).

Are these already implemented in TensorFlow Scala and I've just missed them? Or would it be possible to implement them in TensorFlow Scala?

**Comment by eaplatanios** [comment]
You just use:

```scala
val newGraph = tf.Graph()
tf.createWith(graph = newGraph) {
  // Put everything that needs to go in newGraph here.
}
```

**Comment by Spiess** [comment]
Perfect, thank you, this is exactly what I need!

And just in case someone else looking for the same thing finds this issue: `tf.Graph()` doesn't work for me, but just `Graph()` does.
