### ISSUE TITLE
Are precompiled TF libraries still available?

### ISSUE THREAD

**Issue by ljwagerfield** [eaplatanios/tensorflow_scala#158]
The following doesn't resolve in SBT:
```scala
libraryDependencies += "org.platanios" % "tensorflow" % "0.4.1" classifier "darwin-cpu-x86_64"
```

I'm not familiar with classifiers, but I would expect to see them listed in Maven, no? I can't seem to find them anywhere...

Is the only option to compile TF for myself?

If so, please can you advise which tag/release on the `tensorflow` repository to compile from? (I am using `0.4.1` of `"org.platanios" % "tensorflow"`)

**Comment by eaplatanios** [comment]
Could you please try adding the following to your build file?

```scala
resolvers in ThisBuild += Resolver.sonatypeRepo("snapshots")

...

libraryDependencies += "org.platanios" % "tensorflow" % "0.4.2-SNAPSHOT" classifier "darwin-cpu-x86_64"
```

**Comment by ljwagerfield** [comment]
Yes, that seemed to work, thank you!

Just as an aside: which version of TensorFlow does this use?

I tried compiling TF for myself yesterday, and only got it to work with `r1.13` using `bazel 0.20.0`.

**Comment by DirkToewe** [comment]
There is a `tensorFlowVersion` entry in the [build.sbt](https://github.com/eaplatanios/tensorflow_scala/blob/master/build.sbt#L29) which You can check. Currently that should be `1.11.0`, so `1.12` and `1.13` _should_ work as well. There may be many reasons why the compiled binary is not working. If You get an `undefined symbol` error, take a look at [this issue](https://github.com/eaplatanios/tensorflow_scala/issues/113).
