### ISSUE TITLE
Unable to use tensorflow in scala gradle project

### ISSUE THREAD

**Issue by LakshKD** [eaplatanios/tensorflow_scala#164]
I am able to import the library but unable to import the tensorflow api in scala code. Please help by pointing out how to use tensorflow for scala with scala gradle projects. 

I am able to run tensorflow for scala with sbt but with gradle I am facing above mentioned issues.

**Comment by eaplatanios** [comment]
This should have been resolved by #183 and so I'll go ahead and close it. Please reopen if the issue persists.
