### ISSUE TITLE
Can't import org.platanios.tensorflow.data._

### ISSUE THREAD

**Issue by MiyazawaKohei** [eaplatanios/tensorflow_scala#166]
I tried the MNIST test of README.md on sbt console, and got failed with the error of the title.

I wrote the build.sbt file such like below, but doesn't it enough?
build.sbt:
scalaVersion := "2.12.7"
libraryDependencies += "org.platanios" %% "tensorflow" % "0.4.0"

**Comment by DirkToewe** [comment]
@MiyazawaKohei I believe, You are going to have to depend on tensorflow separately:
```scala
libraryDependencies += "org.platanios" %% "tensorflow-data" % "0.4.0"
```

**Comment by MiyazawaKohei** [comment]
Dear Dirk.
The problem was settled by your solution. Thank you!
