### ISSUE TITLE
SBT Install Documentation is incorrect

### ISSUE THREAD

**Issue by clarkmalmgren** [eaplatanios/tensorflow_scala#176]
SBT installation instructions are not using the scala version-specific instructions which are required. Specifically, `libraryDependencies += "org.platanios" % "tensorflow" % "0.4.0"` should be `libraryDependencies += "org.platanios" %% "tensorflow" % "0.4.0"`

There is a similar problem for the Precompiled Binaries.

**Comment by Jazzpirate** [comment]
Also: 0.4.1 by now :)

**Comment by karlovolf** [comment]
I would suggest opening PR for that :)

**Comment by stefanobaghino** [comment]
Came up on [this discussion on StackOverflow](https://stackoverflow.com/a/62483265/3314107), I opened #183 to fix it. I'm not familiar with Paradox, I'm trying to test it but if you have any guidance I'd be happy to take suggestions. 😄

**Comment by eaplatanios** [comment]
@stefanobaghino I merged the PR and will be updating the website shortly. For future reference, if you want to test the changes made to the paradox site locally, you can use `sbt docs/previewSite`. :)

**Comment by stefanobaghino** [comment]
> @stefanobaghino I merged the PR and will be updating the website shortly. For future reference, if you want to test the changes made to the paradox site locally, you can use `sbt docs/previewSite`. :)

Yeah, the problem was mostly that I know nothing about Tensorflow and the whole part of the build that depended on it failed. But thanks for checking for me and for welcoming the contribution! Cheers!
