### ISSUE TITLE
publish for scala 2.13

### ISSUE THREAD

**Issue by siddhartha-gadgil** [eaplatanios/tensorflow_scala#177]
This would be helpful.

**Comment by eaplatanios** [comment]
This has been implemented in #180. I haven't published artifacts yet but hope to do so soon.

**Comment by siddhartha-gadgil** [comment]
Thanks. Looking forward to this.

**Comment by eaplatanios** [comment]
#180 has now been merged.

**Comment by siddhartha-gadgil** [comment]
Is there going to be a release with this? Thanks.

**Comment by eaplatanios** [comment]
@siddhartha-gadgil there is already a snapshot (`0.5.1-SNAPSHOT`) that I am using for a project. Once I determine it's stable I'm planning to make it a full release.

**Comment by siddhartha-gadgil** [comment]
Is the snapshot on Sonatype?

**Comment by eaplatanios** [comment]
Yes. You can use `resolvers in ThisBuild += Resolver.sonatypeRepo("snapshots")` to get it.

**Comment by siddhartha-gadgil** [comment]
Thanks

regards,
Siddhartha
