### ISSUE TITLE
Error during tf.Saver.fromMetaGraphDef(metaGraphDef), KindCase

### ISSUE THREAD

**Issue by lucaRadicalbit** [eaplatanios/tensorflow_scala#33]
Here is my error:
![1](https://user-images.githubusercontent.com/32895300/32047543-8b145346-ba46-11e7-91d8-b88409e199d3.png)

I'm trying to reload a previous trained TF Model with the Scala API. I checked that inside my my-model.meta file the variables collections is store inside a byte list.
![2](https://user-images.githubusercontent.com/32895300/32046910-b45ef0d2-ba44-11e7-874b-d7e774098932.png)

Looking at the source code I found that here is where the kind of the collection is retrieve
![3](https://user-images.githubusercontent.com/32895300/32046976-dd5ce39a-ba44-11e7-941d-fe8b338e0568.png)

And here I found out the kind associated to byte list is the number 2
![4](https://user-images.githubusercontent.com/32895300/32047000-ee88a8c0-ba44-11e7-8c27-5a6286157eb9.png)

My question is, the `if (kind != 1)` correct ? I expected `if (kind != 2)` than raise error.

**Comment by eaplatanios** [comment]
@lucaRadicalbit You are right. Good catch! :) This should have been fixed now.
