### ISSUE TITLE
Unable to run latest build using intellij

### ISSUE THREAD

**Issue by thak123** [eaplatanios/tensorflow_scala#36]
the latest code is unable to build using sbt.

**Comment by eaplatanios** [comment]
It builds fine for me and it also seems to build fine in Travis CI. Could you please give me some more information on the error you’re getting?

**Comment by thak123** [comment]
[warn] Unable to reparse org.platanios#tensorflow_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:57:09 IST 2017 [warn] Unable to reparse org.platanios#tensorflow-jni_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:55:48 IST 2017 [warn] Unable to reparse org.platanios#tensorflow-api_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:58:06 IST 2017 [warn] Unable to reparse org.platanios#tensorflow-data_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:57:50 IST 2017 [warn] Unable to reparse org.platanios#tensorflow-jni_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:55:48 IST 2017 [warn] Unable to reparse org.platanios#tensorflow-data_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:57:50 IST 2017 [warn] Unable to reparse org.platanios#tensorflow-api_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn] 
Nov 06 05:58:06 IST 2017 [warn] Unable to reparse org.platanios#tensorflow_2.11;0.1.0-SNAPSHOT from sonatype-snapshots, using Mo[warn]

**Comment by thak123** [comment]
Error:Error while importing SBT project:<br/>...<br/><pre>[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ClassNotFoundException: org.jetbrains.sbt.CreateTasks$
[error] Use 'last' for the full log.
[error] Not a valid key: dump-structure (similar: buildStructure)
[error] */*:dump-structure
[error]                   ^</pre><br/>

**Comment by eaplatanios** [comment]
@thak123 I'm not sure what the problem is but it doesn't seem to be related to tensorflow for Scala. It looks like it has to do with your IntelliJ setup for SBT. Are you able to run other Scala projects using IntelliJ and SBT fine?

**Comment by thak123** [comment]
yes. I am able to build other projects. I tried using commandline and got this error [error] java.lang.RuntimeException: No main class detected.

**Comment by thak123** [comment]
its fixed with latest build.. please close the issue

**Comment by eaplatanios** [comment]
@thak123 Great, thanks! :)
