### ISSUE TITLE
Are data, example likely to be published soon?

### ISSUE THREAD

**Issue by siddhartha-gadgil** [eaplatanios/tensorflow_scala#40]
I see a TODO in build.sbt. Got Linear regression working, want to try MNIST (and word2vec)

**Comment by eaplatanios** [comment]
@siddhartha-gadgil The `data` and the `examples` modules are now also included in the publish artifacts. You can use them by specifying one or both of the following dependencies in your project:

```scala
libraryDependencies += "org.platanios" %% "tensorflow-data" % "0.1.0-SNAPSHOT"
libraryDependencies += "org.platanios" %% "tensorflow-examples" % "0.1.0-SNAPSHOT"
```

The artifacts are currently being published and so if your dependencies don't work immediately please wait a few minutes and try again.

**Comment by siddhartha-gadgil** [comment]
Works beautifully. This is brilliant stuff.
The only slight issue is that examples have directories hard-coded in them,
so I can run in a console (as I did) but not just "run"

**Comment by eaplatanios** [comment]
Great, thanks!:) Oh yes. I’m sorry about that. It was because I was using them to test my code. I’ll standardize them a bit and update I_n the next couple of days.
