### ISSUE TITLE
tf.summary.image throws InvalidArgumentException

### ISSUE THREAD

**Issue by csaladin94** [eaplatanios/tensorflow_scala#45]
Hi Anthony,

I've found another bug when using `tf.summary.image`.
Every time I want to use the function, an `InvalidArgumentException` is thrown:
> Exception in thread "main" org.platanios.tensorflow.jni.InvalidArgumentException: More Input() calls than the 2 input_args while building NodeDef 'image' using Op<name=ImageSummary; signature=tag:string, tensor:T -> summary:string; attr=max_images:int,default=3,min=1; attr=T:type,default=DT_FLOAT,allowed=[DT_UINT8, DT_FLOAT, DT_HALF, DT_DOUBLE]; attr=bad_color:tensor,default=Tensor<type: uint8 shape: [4] values: 255 0 0...>>

I think the binding to the native op might be wrong.
Anyways, the following code reproduces the bug for me:

```
import org.platanios.tensorflow.api._

object ImageSummaryBugReproducer {
  def main(args: Array[String]): Unit = {
    val a = tf.reshape(1, Shape(1,1,1,1))
    tf.summary.image("image", a)
  }
}
```

Thanks,
Carlo

**Comment by eaplatanios** [comment]
@csaladin94 Thanks a lot for also finding this! :) There was indeed a bug and I fixed it in the last commit. This fix will also be included in the artifacts I will release tomorrow.

**Comment by csaladin94** [comment]
@eaplatanios Thanks for the fast fix!
Really appreciate your responsiveness.

**Comment by eaplatanios** [comment]
@csaladin94 No problem. Thank you for finding out bugs fast. :)
