### ISSUE TITLE
Snapshot releases have vanished from sonatype

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#52]
https://oss.sonatype.org/index.html#nexus-search;quick~platanios
seems to be empty.

Any idea why?

**Comment by eaplatanios** [comment]
Sorry about that it happened while I was updating the artifacts. I'll publish them again asap and post here. :)

**Comment by eaplatanios** [comment]
@sbrunk The snapshots should be back up now. :)
