### ISSUE TITLE
Dataset.fromGenerator not working

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#54]
Playing with the dataset API I tried the following:

```Scala
import org.platanios.tensorflow.api._

val generator = () => Range(0, 10)
val dataset = tf.data.fromGenerator(generator, INT32, Shape.scalar())
```

This is basically just copied from the docs:
https://github.com/eaplatanios/tensorflow_scala/blob/dce84a0b9f22e7212b3615efe1e232b7a682eaba/api/src/main/scala/org/platanios/tensorflow/api/ops/io/data/Dataset.scala#L265-L266

I get this error though. Do you have any idea what I'm missing here?
```
could not find implicit value for parameter ev: org.platanios.tensorflow.api.ops.io.data.Data.Aux[Int,O,org.platanios.tensorflow.api.types.DataType.Aux[Int],org.platanios.tensorflow.api.core.Shape]
[error]     val dataset = tf.data.fromGenerator(generator, INT32, Shape.scalar())
```

**Comment by sbrunk** [comment]
Thanks for looking into this. Unfortunately, the error still persists.

```
could not find implicit value for parameter ev: org.platanios.tensorflow.api.ops.io.data.Data.Aux[org.platanios.tensorflow.api.tensors.Tensor,O,org.platanios.tensorflow.api.types.DataType.Aux[Int],org.platanios.tensorflow.api.core.Shape]
```

Note that it works (the implicit evidence is summoned) when I use `DataType` explicitly as type param instead of the inferred `DataType.Aux[Int]`
```Scala
val dataset = tf.data.fromGenerator[Tensor, Output, DataType, Shape](generator, INT32, Shape.scalar())
```
but then dataset is of course also of type `Dataset[Tensor, Output, DataType, Shape]`

**Comment by eaplatanios** [comment]
@sbrunk That's interesting. I had created a type trait for that case a while ago and was not using it in this case. I think it's fixed now, but could you please confirm that it also works for you.

**Comment by sbrunk** [comment]
Works for me too. Thanks. :)
