### ISSUE TITLE
proper releasing process

### ISSUE THREAD

**Issue by pawelpanasewicz** [eaplatanios/tensorflow_scala#72]
The project lacks of versioning and releasing which brings a lot of problems when maintaining the codebase depending on it. Furthermore reporting issues can be tricky because there is no way to tell the version of code which caused the problem. Everything has `0.1.0-SNAPSHOT`.

At the moment only snapshot version are published to the OSS sonatype repository everytime overriding previous artifacts. As well there is missing information against which version of tensorflow this library was built which brings another group of problems when setting up environment for work.

**Comment by sbrunk** [comment]
Actually that has already changed. [0.1.0](https://github.com/eaplatanios/tensorflow_scala/releases/tag/v0.1.0) is released with non snapshot binaries on maven central now: https://search.maven.org/#search|ga|1|platanios

Beware that there's a bug #64 in 0.1.0 preventing it to work on Linux but 0.1.1 should be out soon.

**Comment by pawelpanasewicz** [comment]
ohhh, I've just spotted that first release was just created 2 days ago. Well done! What version of tesnsorflow does it work with?

**Comment by pawelpanasewicz** [comment]
There is a `val tensorFlowVersion = "1.5.0-rc1"` in `build.sbt` in [0.1.0](https://github.com/eaplatanios/tensorflow_scala/blob/v0.1.0/build.sbt#L27) release. Does it point to tensorflow version which this library was developed agains?

**Comment by eaplatanios** [comment]
@pawelpanasewicz Yes that is right. I'm currently working on standardizing the release process and the continuous integration environment. It's quite tricky given that I want to provide pre-compiled binaries for different platforms and I need to setup an environment for cross-compiling the native code for all supported platforms. This should be ready soon though. :)

**Comment by eaplatanios** [comment]
Given that there is now a release process in place and that the cross-compiling bug seems to have been fixed in 0.1.1-SNAPSHOT (soon to be 0.1.1), I'll go ahead close this.
