### ISSUE TITLE
0.1.1 broken on OSX; ships Linux TensorFlow binaries

### ISSUE THREAD

**Issue by sbrunk** [eaplatanios/tensorflow_scala#73]
I just tried to update to 0.1.1-SNAPSHOT on OSX, resulting in the following error:
```
[error]   Reason: no suitable image found.  Did find:
[error]         /private/var/folders/74/y5zh_njx423d78dnjjpg3p300000gn/T/tensorflow_scala_native_libraries49902698254112176/libtensorflow.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

So I took quick look at the binaries extracted from the jar, and they seem to be Linux binaries:
```bash
$ file libtensorflow.so 
libtensorflow.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7bd53c8eb71b625e3f3666e47f4fc9603b875039, stripped
```
In fact, it seems both `darwin-cpu-x86_64.jar` and `linux-cpu-x86_64.jar` are identical.

0.1.0 works perfectly on OSX, so I guess there's some glitch in the new build process.

**Comment by eaplatanios** [comment]
@sbrunk This has been fixed in the last snapshot and I'll publish a 0.1.1 release tomorrow. :)

**Comment by sbrunk** [comment]
Awesome, works like a charm now with the 0.1.1 release. Thanks :)
