### ISSUE TITLE
Saving result

### ISSUE THREAD

**Issue by rikvdkleij** [eaplatanios/tensorflow_scala#80]
According to the documentation of `Saver` I can do:
```
val saver = tf.Saver(variables)
```

but that does not compile. Only this compiles:
```
val saver = tf.Saver
```
but I can not call `save` on this saver.

**Comment by rikvdkleij** [comment]
Okay, I found out this it is:
```
val saver = tf.saver()
```

**Comment by eaplatanios** [comment]
I might modify the API a bit eventually to make this smoother. Should I close this issue for now since your problem was resolved?

**Comment by rikvdkleij** [comment]
Yes, issue can be closed. You could fix the scaladoc in `org.platanios.tensorflow.api.ops.variables.Saver`.
