### ISSUE TITLE
Unsatisfied Link Error- While running Tensorflow

### ISSUE THREAD

**Issue by JeyanthVictory** [eaplatanios/tensorflow_scala#85]
I've downloaded .jar file for tensorflow and added that jar file to the class path. While running the program,it shows **Unsatisfied Link Error** exception.
It shows like this
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.`

**Note**  I am using Netbeans.

**Comment by sbrunk** [comment]
I'm not completely sure if I'm up to date but I think Windows is not supported yet. At least there's no jar containing the TensorFlow native library for windows available (even on another platform you'd need to use the jar matching your system i.e. `tensorflow_2.11-0.1.1-linux-cpu-x86_64.jar`).

Perhaps you could try building the TensorFlow native library from source on Windows and see if that works. See http://platanios.org/tensorflow_scala/installation.html#installation-0-dependencies-1 for how to do that.

**Comment by eaplatanios** [comment]
@JeyanthVictory Yes, @sbrunk is right. Windows is not supported yet. They only way to use this library in Windows would be for you to try and compile the TensorFlow native library yourself, separately. I'll close this issue for now, but I can reopen if you have more questions.
