### ISSUE TITLE
Exposing the Tensorflow auto-differentiation functionality in Tensorflow scala

### ISSUE THREAD

**Issue by mandar2812** [eaplatanios/tensorflow_scala#86]
As of now, is it possible to compute gradients of a computation with respect to some tensorflow variable/placeholder using the tensorflow_scala API. If not, this would be a potentially powerful feature which gives access to a crucial component of the Tensorflow API.

**Comment by eaplatanios** [comment]
@mandar2812 Actually the auto-differentiation support in the C API is currently very limited. The Scala API has entirely its own implementation. It’s already exposed through `tf.gradients`. :)

**Comment by mandar2812** [comment]
@eaplatanios Super! Then pardon my ignorance!

**Comment by eaplatanios** [comment]
@mandar2812 To be honest, that's on me. An overview of the library architecture and some tutorials on the website are long overdue, but I've been busy with a research projected haven't gotten to it yet. On the bright side though, the research project is in machine translation and I'll soon be releasing a fully-fledged machine translation package in Scala, using the TensorFlow for Scala API. :)
