### ISSUE TITLE
Extracting native libraries each time JVM starts

### ISSUE THREAD

**Issue by MrVPlusOne** [eaplatanios/tensorflow_scala#90]
Hi, I'm new to Tensorflow-scala. I noticed that every time I run my code, the library extracts native libraries to a temporary directory. Is there a way to prevent this extracting and copying from happening?  I managed to reuse 'libtensorflow.so' and 'libtensorflow_framework.so' by setting the environment variable 'LD_LIBRARY_PATH', but I couldn't figure out how to do this for 'libtensorflow_jni.so' and 'libtensorflow_ops.so'.

**Comment by eaplatanios** [comment]
@MrVPlusOne It's true those libraries are extracted every time and that's because they're package in the distributed JAR file. It's only a few KBs in size and so should not contribute a performance penalty. Are you experiencing a significant slow down due to the extraction?

**Comment by MrVPlusOne** [comment]
No, I didn't experience any significant slowdown. It's just a little annoying that each time the library has to do this. Nevermind then.

**Comment by eaplatanios** [comment]
I could change the logging level to debug for the messages. Would that be better?

**Comment by MrVPlusOne** [comment]
I guess so?

**Comment by eaplatanios** [comment]
Done! :)
