### ISSUE TITLE
adding bindings to scala collider

### ISSUE THREAD

**Issue by tmm2018** [eaplatanios/tensorflow_scala#94]
it would be really nice, to bind this with:
- https://github.com/Sciss/ScalaCollider

**Comment by eaplatanios** [comment]
@tmm2018 I'd be happy to help someone with this, but unfortunately, I won't be able to work on it myself, as I'm not familiar with ScalaCollider at all and I don't really have any free time to invest in this.

**Comment by tmm2018** [comment]
that sounds reasonable. we can't do everything that pops up to our minds. sometimes. doing small things, but really investing on them, and making them as well as we can, is the best thing we can do.

**Comment by eaplatanios** [comment]
I'll close this for now because I feel it won't be tackled any time soon, but I will add an extension label so people can access it easily (I plan to add contribution guidelines soon and "extensions" in that sense will be mentioned there so people can take them on if they want to).
